package server

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z metaClient) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Account == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Service == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Cluster == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not empty
		// string "acc"
		o = append(o, 0xa3, 0x61, 0x63, 0x63)
		o = msgp.AppendString(o, z.Account)
	}
	if (zb0001Mask & 0x2) == 0 { // if not empty
		// string "svc"
		o = append(o, 0xa3, 0x73, 0x76, 0x63)
		o = msgp.AppendString(o, z.Service)
	}
	if (zb0001Mask & 0x4) == 0 { // if not empty
		// string "cluster"
		o = append(o, 0xa7, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
		o = msgp.AppendString(o, z.Cluster)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *metaClient) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "acc":
			z.Account, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Account")
				return
			}
		case "svc":
			z.Service, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Service")
				return
			}
		case "cluster":
			z.Cluster, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cluster")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z metaClient) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Account) + 4 + msgp.StringPrefixSize + len(z.Service) + 8 + msgp.StringPrefixSize + len(z.Cluster)
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *metaConsumerAssignment) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(7)
	var zb0001Mask uint8 /* 7 bits */
	_ = zb0001Mask
	if z.Client == (metaClient{}) {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.State == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not empty
		// string "client"
		o = append(o, 0xa6, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74)
		// omitempty: check for empty values
		zb0002Len := uint32(3)
		var zb0002Mask uint8 /* 3 bits */
		_ = zb0002Mask
		if z.Client.Account == "" {
			zb0002Len--
			zb0002Mask |= 0x1
		}
		if z.Client.Service == "" {
			zb0002Len--
			zb0002Mask |= 0x2
		}
		if z.Client.Cluster == "" {
			zb0002Len--
			zb0002Mask |= 0x4
		}
		// variable map header, size zb0002Len
		o = append(o, 0x80|uint8(zb0002Len))
		if (zb0002Mask & 0x1) == 0 { // if not empty
			// string "acc"
			o = append(o, 0xa3, 0x61, 0x63, 0x63)
			o = msgp.AppendString(o, z.Client.Account)
		}
		if (zb0002Mask & 0x2) == 0 { // if not empty
			// string "svc"
			o = append(o, 0xa3, 0x73, 0x76, 0x63)
			o = msgp.AppendString(o, z.Client.Service)
		}
		if (zb0002Mask & 0x4) == 0 { // if not empty
			// string "cluster"
			o = append(o, 0xa7, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
			o = msgp.AppendString(o, z.Client.Cluster)
		}
	}
	// string "created"
	o = append(o, 0xa7, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64)
	o = msgp.AppendInt64(o, z.CreatedNS)
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "stream"
	o = append(o, 0xa6, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d)
	o = msgp.AppendString(o, z.Stream)
	// string "consumer"
	o = append(o, 0xa8, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72)
	o = msgp.AppendBytes(o, z.ConfigJSON)
	// string "group"
	o = append(o, 0xa5, 0x67, 0x72, 0x6f, 0x75, 0x70)
	o, err = z.Group.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Group")
		return
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// string "state"
		o = append(o, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x65)
		o = msgp.AppendBytes(o, z.State)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *metaConsumerAssignment) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "client":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Client")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Client")
					return
				}
				switch msgp.UnsafeString(field) {
				case "acc":
					z.Client.Account, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Account")
						return
					}
				case "svc":
					z.Client.Service, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Service")
						return
					}
				case "cluster":
					z.Client.Cluster, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Cluster")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client")
						return
					}
				}
			}
		case "created":
			z.CreatedNS, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedNS")
				return
			}
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "stream":
			z.Stream, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Stream")
				return
			}
		case "consumer":
			z.ConfigJSON, bts, err = msgp.ReadBytesBytes(bts, z.ConfigJSON)
			if err != nil {
				err = msgp.WrapError(err, "ConfigJSON")
				return
			}
		case "group":
			bts, err = z.Group.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Group")
				return
			}
		case "state":
			z.State, bts, err = msgp.ReadBytesBytes(bts, z.State)
			if err != nil {
				err = msgp.WrapError(err, "State")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *metaConsumerAssignment) Msgsize() (s int) {
	s = 1 + 7 + 1 + 4 + msgp.StringPrefixSize + len(z.Client.Account) + 4 + msgp.StringPrefixSize + len(z.Client.Service) + 8 + msgp.StringPrefixSize + len(z.Client.Cluster) + 8 + msgp.Int64Size + 5 + msgp.StringPrefixSize + len(z.Name) + 7 + msgp.StringPrefixSize + len(z.Stream) + 9 + msgp.BytesPrefixSize + len(z.ConfigJSON) + 6 + z.Group.Msgsize() + 6 + msgp.BytesPrefixSize + len(z.State)
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *metaRaftGroup) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(6)
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	if z.Cluster == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Preferred == "" {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.ScaleUp == false {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	// string "name"
	o = append(o, 0xa4, 0x6e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "peers"
	o = append(o, 0xa5, 0x70, 0x65, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Peers)))
	for za0001 := range z.Peers {
		o = msgp.AppendString(o, z.Peers[za0001])
	}
	// string "store"
	o = append(o, 0xa5, 0x73, 0x74, 0x6f, 0x72, 0x65)
	o = msgp.AppendUint8(o, z.Storage)
	if (zb0001Mask & 0x8) == 0 { // if not empty
		// string "cluster"
		o = append(o, 0xa7, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
		o = msgp.AppendString(o, z.Cluster)
	}
	if (zb0001Mask & 0x10) == 0 { // if not empty
		// string "preferred"
		o = append(o, 0xa9, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64)
		o = msgp.AppendString(o, z.Preferred)
	}
	if (zb0001Mask & 0x20) == 0 { // if not empty
		// string "scale_up"
		o = append(o, 0xa8, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x75, 0x70)
		o = msgp.AppendBool(o, z.ScaleUp)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *metaRaftGroup) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "peers":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Peers")
				return
			}
			if cap(z.Peers) >= int(zb0002) {
				z.Peers = (z.Peers)[:zb0002]
			} else {
				z.Peers = make([]string, zb0002)
			}
			for za0001 := range z.Peers {
				z.Peers[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Peers", za0001)
					return
				}
			}
		case "store":
			z.Storage, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Storage")
				return
			}
		case "cluster":
			z.Cluster, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cluster")
				return
			}
		case "preferred":
			z.Preferred, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Preferred")
				return
			}
		case "scale_up":
			z.ScaleUp, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ScaleUp")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *metaRaftGroup) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Peers {
		s += msgp.StringPrefixSize + len(z.Peers[za0001])
	}
	s += 6 + msgp.Uint8Size + 8 + msgp.StringPrefixSize + len(z.Cluster) + 10 + msgp.StringPrefixSize + len(z.Preferred) + 9 + msgp.BoolSize
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *metaStreamAssignment) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(6)
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	if z.Client == (metaClient{}) {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not empty
		// string "client"
		o = append(o, 0xa6, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74)
		// omitempty: check for empty values
		zb0002Len := uint32(3)
		var zb0002Mask uint8 /* 3 bits */
		_ = zb0002Mask
		if z.Client.Account == "" {
			zb0002Len--
			zb0002Mask |= 0x1
		}
		if z.Client.Service == "" {
			zb0002Len--
			zb0002Mask |= 0x2
		}
		if z.Client.Cluster == "" {
			zb0002Len--
			zb0002Mask |= 0x4
		}
		// variable map header, size zb0002Len
		o = append(o, 0x80|uint8(zb0002Len))
		if (zb0002Mask & 0x1) == 0 { // if not empty
			// string "acc"
			o = append(o, 0xa3, 0x61, 0x63, 0x63)
			o = msgp.AppendString(o, z.Client.Account)
		}
		if (zb0002Mask & 0x2) == 0 { // if not empty
			// string "svc"
			o = append(o, 0xa3, 0x73, 0x76, 0x63)
			o = msgp.AppendString(o, z.Client.Service)
		}
		if (zb0002Mask & 0x4) == 0 { // if not empty
			// string "cluster"
			o = append(o, 0xa7, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
			o = msgp.AppendString(o, z.Client.Cluster)
		}
	}
	// string "created"
	o = append(o, 0xa7, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64)
	o = msgp.AppendInt64(o, z.CreatedNS)
	// string "stream"
	o = append(o, 0xa6, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d)
	o = msgp.AppendBytes(o, z.ConfigJSON)
	// string "group"
	o = append(o, 0xa5, 0x67, 0x72, 0x6f, 0x75, 0x70)
	o, err = z.Group.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Group")
		return
	}
	// string "sync"
	o = append(o, 0xa4, 0x73, 0x79, 0x6e, 0x63)
	o = msgp.AppendString(o, z.Sync)
	// string "consumers"
	o = append(o, 0xa9, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Consumers)))
	for za0001 := range z.Consumers {
		o, err = z.Consumers[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Consumers", za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *metaStreamAssignment) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "client":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Client")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Client")
					return
				}
				switch msgp.UnsafeString(field) {
				case "acc":
					z.Client.Account, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Account")
						return
					}
				case "svc":
					z.Client.Service, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Service")
						return
					}
				case "cluster":
					z.Client.Cluster, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client", "Cluster")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Client")
						return
					}
				}
			}
		case "created":
			z.CreatedNS, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedNS")
				return
			}
		case "stream":
			z.ConfigJSON, bts, err = msgp.ReadBytesBytes(bts, z.ConfigJSON)
			if err != nil {
				err = msgp.WrapError(err, "ConfigJSON")
				return
			}
		case "group":
			bts, err = z.Group.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Group")
				return
			}
		case "sync":
			z.Sync, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Sync")
				return
			}
		case "consumers":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Consumers")
				return
			}
			if cap(z.Consumers) >= int(zb0003) {
				z.Consumers = (z.Consumers)[:zb0003]
			} else {
				z.Consumers = make([]metaConsumerAssignment, zb0003)
			}
			for za0001 := range z.Consumers {
				bts, err = z.Consumers[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Consumers", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *metaStreamAssignment) Msgsize() (s int) {
	s = 1 + 7 + 1 + 4 + msgp.StringPrefixSize + len(z.Client.Account) + 4 + msgp.StringPrefixSize + len(z.Client.Service) + 8 + msgp.StringPrefixSize + len(z.Client.Cluster) + 8 + msgp.Int64Size + 7 + msgp.BytesPrefixSize + len(z.ConfigJSON) + 6 + z.Group.Msgsize() + 5 + msgp.StringPrefixSize + len(z.Sync) + 10 + msgp.ArrayHeaderSize
	for za0001 := range z.Consumers {
		s += z.Consumers[za0001].Msgsize()
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z wsaList) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for za0001 := range z {
		o, err = z[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, za0001)
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *wsaList) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(wsaList, zb0002)
	}
	for zb0001 := range *z {
		bts, err = (*z)[zb0001].UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z wsaList) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0003 := range z {
		s += z[zb0003].Msgsize()
	}
	return
}
