package server

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z clientInfoSnap) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// omitempty: check for empty values
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Account == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Service == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Cluster == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))
	if zb0001Len == 0 {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not empty
		// string "acc"
		o = append(o, 0xa3, 0x61, 0x63, 0x63)
		o = msgp.AppendString(o, z.Account)
	}
	if (zb0001Mask & 0x2) == 0 { // if not empty
		// string "svc"
		o = append(o, 0xa3, 0x73, 0x76, 0x63)
		o = msgp.AppendString(o, z.Service)
	}
	if (zb0001Mask & 0x4) == 0 { // if not empty
		// string "cluster"
		o = append(o, 0xa7, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
		o = msgp.AppendString(o, z.Cluster)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *clientInfoSnap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "acc":
			z.Account, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Account")
				return
			}
		case "svc":
			z.Service, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Service")
				return
			}
		case "cluster":
			z.Cluster, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Cluster")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z clientInfoSnap) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.Account) + 4 + msgp.StringPrefixSize + len(z.Service) + 8 + msgp.StringPrefixSize + len(z.Cluster)
	return
}
